# Generated by Django 4.2.6 on 2023-10-17 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='exixtencias',
            new_name='existencias',
        ),
    ]
