# Generated by Django 4.2.6 on 2023-10-17 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_rename_exixtencias_producto_existencias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_compra',
            name='subtotal',
            field=models.FloatField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='existencias',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_compra',
            field=models.FloatField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.FloatField(max_length=6, null=True),
        ),
    ]
