# Generated by Django 4.2.6 on 2023-10-14 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_compra_alter_empleado_usuario_alter_producto_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle_compra',
            old_name='producto',
            new_name='tipo_prenda',
        ),
    ]
