# Generated by Django 4.2.6 on 2023-10-17 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_alter_producto_existencias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='existencias',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_compra',
            field=models.FloatField(blank=True, default=0, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.FloatField(blank=True, default=0, max_length=6, null=True),
        ),
    ]
