# Generated by Django 4.2.6 on 2023-10-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_alter_producto_existencias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_compra',
            field=models.FloatField(blank=True, max_length=6, null=True),
        ),
    ]
