# Generated by Django 4.2.6 on 2023-10-17 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_rename_nombre_categoria_producto_nom_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nom_categoria',
            new_name='nombre_categoria',
        ),
    ]
