# Generated by Django 4.2.6 on 2023-10-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_rename_nom_categoria_producto_nombre_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_compra',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detalle_compra',
            name='precio_compra',
            field=models.FloatField(blank=True, default=0, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_compra',
            name='subtotal',
            field=models.FloatField(blank=True, default=0, max_length=6, null=True),
        ),
    ]
