# Generated by Django 4.2.6 on 2023-11-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0011_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='genero',
            field=models.IntegerField(choices=[[0, 'Mujer'], [1, 'Hombre']]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='talla',
            field=models.CharField(max_length=20),
        ),
    ]
